/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;
import classes.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author capsi
 */
public class CadastroMecanicos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroMecanicos.class.getName());
    final ArrayList<Profissional> listaProfissional;
    FormPrincipal principal;
    /**
     * Creates new form CadastroMecanicos
     */
    public CadastroMecanicos(java.awt.Frame parent, boolean modal, ArrayList<Profissional> listaProfissional) {
        super(parent, modal);
        this.listaProfissional = listaProfissional;
        principal = (FormPrincipal) this.getParent();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ImprimirBtn = new javax.swing.JButton();
        cbNome = new javax.swing.JCheckBox();
        cbCertificacao = new javax.swing.JCheckBox();
        cbTelefone = new javax.swing.JCheckBox();
        cbArea = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        jButton1.setText("InserirMecanico");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("EditarInfo");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("ExcluirMecanico");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        ImprimirBtn.setText("Imprimir");
        ImprimirBtn.addActionListener(this::ImprimirBtnActionPerformed);

        cbNome.setText("Nome");

        cbCertificacao.setText("Certificação");

        cbTelefone.setText("Telefone");

        cbArea.setText("AreaEspecializacao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbNome)
                                        .addGap(52, 52, 52)
                                        .addComponent(cbTelefone))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbCertificacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbArea)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ImprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbNome)
                            .addComponent(cbTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCertificacao)
                            .addComponent(cbArea)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImprimirBtn)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o código do mecânico:"));
        Profissional mecanicoAux = principal.buscarProfissionalCodigo(codigo);
        
        if (mecanicoAux == null) {
            String nome =  JOptionPane.showInputDialog("Digite o nome completo:");
            ArrayList<String> telefones = new ArrayList<>();
            
            String continuar = "S";

            while (continuar.equalsIgnoreCase("S")) {

                String telefone = JOptionPane.showInputDialog("Digite um telefone:");

                telefones.add(telefone);

                continuar = JOptionPane.showInputDialog("Deseja adicionar outro telefone? S/N");
            }
            
            int numCertificacao = Integer.parseInt(JOptionPane.showInputDialog("Digite o número de certificação:"));
           
            String areaEspec = JOptionPane.showInputDialog("Digite a área: Motor, Suspensão, Elétrica ou Funilaria");
            
            listaProfissional.add(new Mecanico(codigo,nome,telefones,numCertificacao,areaEspec));
            
        } 
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ImprimirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirBtnActionPerformed
        taSaida.setText("");

        for (Profissional p : listaProfissional) {
            taSaida.append(p.toString() + "\n");
        }
    }//GEN-LAST:event_ImprimirBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o código do mecânico:"));

        Profissional p = principal.buscarProfissionalCodigo(codigo);

        if (p != null) {
            listaProfissional.remove(p);
            JOptionPane.showMessageDialog(null, "Mecânico excluído com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Mecânico não encontrado!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int codigo = Integer.parseInt(
        JOptionPane.showInputDialog("Digite o código do mecânico:")
    );

    Profissional p = principal.buscarProfissionalCodigo(codigo);

    if (p != null && p instanceof Mecanico) {

        Mecanico m = (Mecanico) p;

        if (cbNome.isSelected()) {
            String novoNome = JOptionPane.showInputDialog("Digite o novo nome:");
            m.setNomeCompleto(novoNome);
        }

        if (cbTelefone.isSelected()) {
            ArrayList<String> novosTelefones = new ArrayList<>();

            String continuar = "S";

            while (continuar.equalsIgnoreCase("S")) {
                String telefone = JOptionPane.showInputDialog("Digite um telefone:");
                novosTelefones.add(telefone);

                continuar = JOptionPane.showInputDialog("Deseja adicionar outro telefone? S/N");
            }

            m.setTelefones(novosTelefones);
        }

        if (cbCertificacao.isSelected()) {
            int novaCertificacao = Integer.parseInt(
                JOptionPane.showInputDialog("Digite a nova certificação:")
            );
            m.setNumCertificacao(novaCertificacao);
        }

        if (cbArea.isSelected()) {
            String novaArea = JOptionPane.showInputDialog(
                "Digite a nova área: Motor, Suspensão, Elétrica ou Funilaria"
            );
            m.setAreaEspec(novaArea);
        }

        JOptionPane.showMessageDialog(null, "Mecânico editado com sucesso!");

    } else {
        JOptionPane.showMessageDialog(null, "Mecânico não encontrado!");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImprimirBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbArea;
    private javax.swing.JCheckBox cbCertificacao;
    private javax.swing.JCheckBox cbNome;
    private javax.swing.JCheckBox cbTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
