/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;
import classes.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author capsi
 */
public class CadastroFichaManutencao extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroFichaManutencao.class.getName());
    private ArrayList<FichaManutencao> listaFichas;
    private ArrayList<Veiculo> listaVeiculos;
    private ArrayList<Categoria> listaCategorias;
    private ArrayList<Profissional> listaProfissional;
    private FormPrincipal principal;
    /**
     * Creates new form CadastroFichaManutencao
     * @param parent
     * @param modal
     * @param listaFichas
     * @param listaVeiculos
     * @param listaCategorias
     * @param listaProfissional
     */
    public CadastroFichaManutencao(java.awt.Frame parent, boolean modal,
            ArrayList<FichaManutencao> listaFichas,
            ArrayList<Veiculo> listaVeiculos,
            ArrayList<Categoria> listaCategorias,
            ArrayList<Profissional> listaProfissional) {
        super(parent, modal);
        this.listaFichas = listaFichas;
        this.listaVeiculos = listaVeiculos;
        this.listaCategorias = listaCategorias;
        this.listaProfissional = listaProfissional;
        this.principal = (FormPrincipal) parent;
        initComponents();
        setLocationRelativeTo(parent);
    }
    private int lerInteiro(String mensagem) {
        while (true) {
            try {
                String texto = JOptionPane.showInputDialog(mensagem);

                if (texto == null) {
                    return -1;
                }

                if (texto.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Campo obrigatório!");
                } else {
                    return Integer.parseInt(texto);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Digite apenas números!");
            }
        }
    }
     private double lerDouble(String mensagem) {
        while (true) {
            try {
                String texto = JOptionPane.showInputDialog(mensagem);

                if (texto == null) {
                    return -1;
                }

                texto = texto.replace(",", ".");

                if (texto.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Campo obrigatório!");
                } else {
                    return Double.parseDouble(texto);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Digite um valor numérico válido!");
            }
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInserirFicha = new javax.swing.JButton();
        btnEditarReparo = new javax.swing.JButton();
        btnInserirReparo = new javax.swing.JButton();
        btnExcluirFicha = new javax.swing.JButton();
        btnListarFicha = new javax.swing.JButton();
        btnRelatorioCompleto = new javax.swing.JButton();
        btnDadosTeste = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnInserirFicha.setText("Inserir Ficha");
        btnInserirFicha.addActionListener(this::btnInserirFichaActionPerformed);

        btnEditarReparo.setText("Editar Reparo");
        btnEditarReparo.addActionListener(this::btnEditarReparoActionPerformed);

        btnInserirReparo.setText("Inserir Reparo");
        btnInserirReparo.addActionListener(this::btnInserirReparoActionPerformed);

        btnExcluirFicha.setText("Excluir Ficha");
        btnExcluirFicha.addActionListener(this::btnExcluirFichaActionPerformed);

        btnListarFicha.setText("Listar Ficha");
        btnListarFicha.addActionListener(this::btnListarFichaActionPerformed);

        btnRelatorioCompleto.setText("Relatorio Completo");
        btnRelatorioCompleto.addActionListener(this::btnRelatorioCompletoActionPerformed);

        btnDadosTeste.setText("Dados Teste");
        btnDadosTeste.addActionListener(this::btnDadosTesteActionPerformed);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnDadosTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserirFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarReparo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInserirReparo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorioCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListarFicha, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnInserirFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarReparo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnInserirReparo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluirFicha, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnRelatorioCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDadosTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarReparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarReparoActionPerformed
        // TODO add your handling code here:
         int codigoFicha = lerInteiro("Digite o código da ficha:");

        if (codigoFicha == -1) {
            return;
        }

        FichaManutencao ficha = principal.buscarFichaCodigo(codigoFicha);

        if (ficha == null) {
            JOptionPane.showMessageDialog(null, "Ficha não encontrada.");
            return;
        }

        int codigoReparo = lerInteiro("Digite o código do reparo:");

        if (codigoReparo == -1) {
            return;
        }

        Reparo reparo = null;

        for (Reparo r : ficha.getListaReparos()) {
            if (r.getCodigo() == codigoReparo) {
                reparo = r;
                break;
            }
        }

        if (reparo == null) {
            JOptionPane.showMessageDialog(null, "Reparo não encontrado.");
            return;
        }

        String novoNome = JOptionPane.showInputDialog("Digite o novo nome:", reparo.getNome());

        if (novoNome != null && !novoNome.trim().isEmpty()) {
            reparo.setNome(novoNome);
        }

        double novoCusto = lerDouble("Digite o novo custo:");

        if (novoCusto != -1) {
            reparo.setCusto(novoCusto);
        }

        String novoRelato = JOptionPane.showInputDialog("Digite o novo relato:", reparo.getRelato());

        if (novoRelato != null) {
            reparo.setRelato(novoRelato);
        }

        int novoCodigoCategoria = lerInteiro("Digite o novo código da categoria:");

        if (novoCodigoCategoria != -1) {
            Categoria novaCategoria = principal.buscarCategoriaCodigo(novoCodigoCategoria);

            if (novaCategoria != null) {
                reparo.setCategoria(novaCategoria);
            } else {
                JOptionPane.showMessageDialog(null, "Categoria não encontrada. Categoria antiga mantida.");
            }
        }

        int novoCodigoProfissional = lerInteiro("Digite o novo código do profissional:");

        if (novoCodigoProfissional != -1) {
            Profissional novoProfissional = principal.buscarProfissionalCodigo(novoCodigoProfissional);

            if (novoProfissional != null) {
                reparo.setProfissional(novoProfissional);
            } else {
                JOptionPane.showMessageDialog(null, "Profissional não encontrado. Profissional antigo mantido.");
            }
        }

        JOptionPane.showMessageDialog(null, "Reparo editado com sucesso.");
    }//GEN-LAST:event_btnEditarReparoActionPerformed

    private void btnExcluirFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFichaActionPerformed
        // TODO add your handling code here:
        int codigo = lerInteiro("Digite o código da ficha:");

        if (codigo == -1) {
            return;
        }

        FichaManutencao ficha = principal.buscarFichaCodigo(codigo);

        if (ficha == null) {
            JOptionPane.showMessageDialog(null, "Ficha não encontrada.");
            return;
        }

        listaFichas.remove(ficha);

        JOptionPane.showMessageDialog(null, "Ficha excluída com sucesso.");
    
        
    }//GEN-LAST:event_btnExcluirFichaActionPerformed

    private void btnListarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFichaActionPerformed
        // TODO add your handling code here:
         taSaida.setText("");

        if (listaFichas.isEmpty()) {
            taSaida.setText("Nenhuma ficha cadastrada.");
            return;
        }

        for (FichaManutencao f : listaFichas) {
            taSaida.append(f.toString() + "\n\n");
        }
        
    }//GEN-LAST:event_btnListarFichaActionPerformed

    private void btnRelatorioCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioCompletoActionPerformed
        taSaida.setText("");

        if (listaFichas.isEmpty()) {
            taSaida.setText("Nenhuma ficha de manutenção cadastrada.");
            return;
        }

        for (FichaManutencao ficha : listaFichas) {
            taSaida.append(ficha.retornarFichaManutencaoCompleta());
            taSaida.append("\n\n====================================\n\n");
        }
    }//GEN-LAST:event_btnRelatorioCompletoActionPerformed

    private void btnInserirFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirFichaActionPerformed
        // TODO add your handling code here:
        if (listaVeiculos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre um veículo antes de criar uma ficha.");
            return;
        }

        int codigo = lerInteiro("Digite o código da ficha:");

        if (codigo == -1) {
            return;
        }

        FichaManutencao fichaExistente = principal.buscarFichaCodigo(codigo);

        if (fichaExistente != null) {
            JOptionPane.showMessageDialog(null, "Já existe uma ficha com esse código.");
            return;
        }

        String placa = JOptionPane.showInputDialog("Digite a placa do veículo:");

        if (placa == null || placa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Placa obrigatória.");
            return;
        }

        Veiculo veiculo = principal.buscarVeiculoPlaca(placa);

        if (veiculo == null) {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado.");
            return;
        }

        FichaManutencao fichaPorPlaca = principal.buscarFichaPorPlaca(placa);

        if (fichaPorPlaca != null) {
            JOptionPane.showMessageDialog(null, "Esse veículo já possui ficha de manutenção.");
            return;
        }

        listaFichas.add(new FichaManutencao(codigo, veiculo));

        JOptionPane.showMessageDialog(null, "Ficha cadastrada com sucesso.");
    }//GEN-LAST:event_btnInserirFichaActionPerformed

    private void btnInserirReparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirReparoActionPerformed
        // TODO add your handling code here:
        if (listaFichas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre uma ficha antes de inserir reparos.");
            return;
        }

        if (listaCategorias.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre uma categoria antes de inserir reparos.");
            return;
        }

        if (listaProfissional.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre um mecânico antes de inserir reparos.");
            return;
        }

        int codigoFicha = lerInteiro("Digite o código da ficha:");

        if (codigoFicha == -1) {
            return;
        }

        FichaManutencao ficha = principal.buscarFichaCodigo(codigoFicha);

        if (ficha == null) {
            JOptionPane.showMessageDialog(null, "Ficha não encontrada.");
            return;
        }

        String nome = JOptionPane.showInputDialog("Digite o nome do reparo:");

        if (nome == null || nome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome do reparo obrigatório.");
            return;
        }

        double custo = lerDouble("Digite o custo do reparo:");

        if (custo == -1) {
            return;
        }

        String relato = JOptionPane.showInputDialog("Digite o relato do reparo:");

        if (relato == null) {
            relato = "";
        }

        int codigoCategoria = lerInteiro("Digite o código da categoria:");

        if (codigoCategoria == -1) {
            return;
        }

        Categoria categoria = principal.buscarCategoriaCodigo(codigoCategoria);

        if (categoria == null) {
            JOptionPane.showMessageDialog(null, "Categoria não encontrada.");
            return;
        }

        int codigoProfissional = lerInteiro("Digite o código do profissional:");

        if (codigoProfissional == -1) {
            return;
        }

        Profissional profissional = principal.buscarProfissionalCodigo(codigoProfissional);

        if (profissional == null) {
            JOptionPane.showMessageDialog(null, "Profissional não encontrado.");
            return;
        }

        ficha.inserirReparo(nome, custo, relato, categoria, profissional);

        JOptionPane.showMessageDialog(null, "Reparo inserido com sucesso.");
    }//GEN-LAST:event_btnInserirReparoActionPerformed

    private void btnDadosTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosTesteActionPerformed
        // TODO add your handling code here:
         if (listaVeiculos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre veículos de teste primeiro na tela de veículos.");
            return;
        }

        if (listaCategorias.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre categorias de teste primeiro na tela de categorias.");
            return;
        }

        if (listaProfissional.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre mecânicos de teste primeiro na tela de mecânicos.");
            return;
        }

        Veiculo veiculo = listaVeiculos.get(0);

        if (principal.buscarFichaPorPlaca(veiculo.getPlaca()) != null) {
            JOptionPane.showMessageDialog(null, "O primeiro veículo da lista já possui ficha.");
            return;
        }

        int codigoFicha = 1;

        while (principal.buscarFichaCodigo(codigoFicha) != null) {
            codigoFicha++;
        }

        FichaManutencao ficha = new FichaManutencao(codigoFicha, veiculo);

        Categoria categoria = listaCategorias.get(0);
        Profissional profissional = listaProfissional.get(0);

        ficha.inserirReparo(
                "Troca de pastilhas",
                250.00,
                "Pastilhas desgastadas.",
                categoria,
                profissional
        );

        ficha.inserirReparo(
                "Alinhamento",
                120.00,
                "Veículo puxando para a direita.",
                categoria,
                profissional
        );

        listaFichas.add(ficha);

        JOptionPane.showMessageDialog(null, "Ficha de teste cadastrada com reparos.");
        
    }//GEN-LAST:event_btnDadosTesteActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDadosTeste;
    private javax.swing.JButton btnEditarReparo;
    private javax.swing.JButton btnExcluirFicha;
    private javax.swing.JButton btnInserirFicha;
    private javax.swing.JButton btnInserirReparo;
    private javax.swing.JButton btnListarFicha;
    private javax.swing.JButton btnRelatorioCompleto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
