/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import classes.Categoria;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author capsi
 */
public class CadastroCategorias extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroCategorias.class.getName());
    private ArrayList<Categoria> listaCategorias;
    private FormPrincipal principal;
    /**
     * Creates new form CadastrarCategorias
     */
    public CadastroCategorias(java.awt.Frame parent, boolean modal, ArrayList<Categoria> listaCategorias) {
        super(parent, modal);
        this.listaCategorias = listaCategorias;
        this.principal = (FormPrincipal) parent;
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Inserir");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Editar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Excluir");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Listar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        jButton5.setText("Carregar Dados de Teste");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o código da categoria:"));

        Categoria categoriaAux = principal.buscarCategoriaCodigo(codigo);

        if (categoriaAux != null) {
            JOptionPane.showMessageDialog(null, "Já existe uma categoria com esse código!");
            return;
        }

        String nome = JOptionPane.showInputDialog("Digite o nome da categoria:");

        if (nome == null || nome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome obrigatório!");
            return;
        }

        listaCategorias.add(new Categoria(codigo, nome));

        JOptionPane.showMessageDialog(null, "Categoria cadastrada com sucesso!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o código da categoria:"));

        Categoria categoriaAux = principal.buscarCategoriaCodigo(codigo);

        if (categoriaAux == null) {
            JOptionPane.showMessageDialog(null, "Categoria não encontrada!");
            return;
        }

        String novoNome = JOptionPane.showInputDialog(
                "Digite o novo nome:",
                categoriaAux.getNome()
        );

        if (novoNome == null || novoNome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome inválido!");
            return;
        }

        categoriaAux.setNome(novoNome);

        JOptionPane.showMessageDialog(null, "Categoria editada com sucesso!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int codigo = Integer.parseInt(
            JOptionPane.showInputDialog("Digite o código da categoria:")
        );

        Categoria categoriaAux = principal.buscarCategoriaCodigo(codigo);

        if (categoriaAux == null) {
            JOptionPane.showMessageDialog(null, "Categoria não encontrada!");
            return;
        }

        listaCategorias.remove(categoriaAux);

        JOptionPane.showMessageDialog(null, "Categoria excluída com sucesso!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        taSaida.setText("");

        if (listaCategorias.isEmpty()) {
            taSaida.setText("Nenhuma categoria cadastrada.");
            return;
        }

        for (Categoria c : listaCategorias) {
            taSaida.append(c.toString() + "\n\n");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (principal.buscarCategoriaCodigo(1) == null) {
            listaCategorias.add(new Categoria(1, "Motor"));
        }

        if (principal.buscarCategoriaCodigo(2) == null) {
            listaCategorias.add(new Categoria(2, "Freios"));
        }

        if (principal.buscarCategoriaCodigo(3) == null) {
            listaCategorias.add(new Categoria(3, "Suspensão"));
        }

        if (principal.buscarCategoriaCodigo(4) == null) {
            listaCategorias.add(new Categoria(4, "Sistema elétrico"));
        }

        if (principal.buscarCategoriaCodigo(5) == null) {
            listaCategorias.add(new Categoria(5, "Estética automotiva"));
        }

        JOptionPane.showMessageDialog(null, "Categorias de exemplo adicionadas!");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
