/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;
import classes.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author capsi
 */
public class CadastroMecanicos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroMecanicos.class.getName());
    final ArrayList<Profissional> listaProfissional;
    FormPrincipal principal;
    /**
     * Creates new form CadastroMecanicos
     */
    public CadastroMecanicos(java.awt.Frame parent, boolean modal, ArrayList<Profissional> listaProfissional) {
        super(parent, modal);
        this.listaProfissional = listaProfissional;
        principal = (FormPrincipal) this.getParent();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ImprimirBtn = new javax.swing.JButton();
        cbNome = new javax.swing.JCheckBox();
        cbCertificacao = new javax.swing.JCheckBox();
        cbTelefone = new javax.swing.JCheckBox();
        cbArea = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        jButton1.setText("InserirMecanico");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("EditarInfo");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("ExcluirMecanico");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        ImprimirBtn.setText("Imprimir");
        ImprimirBtn.addActionListener(this::ImprimirBtnActionPerformed);

        cbNome.setText("Nome");

        cbCertificacao.setText("Certificação");

        cbTelefone.setText("Telefone");

        cbArea.setText("AreaEspecializacao");

        jButton4.setText("Cadastrar Dados de Teste");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ImprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbNome)
                                                .addGap(52, 52, 52)
                                                .addComponent(cbTelefone))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbCertificacao)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbArea)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbNome)
                            .addComponent(cbTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCertificacao)
                            .addComponent(cbArea)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o código do mecânico:"));
        Profissional mecanicoAux = principal.buscarProfissionalCodigo(codigo);
        
        if (mecanicoAux == null) {
            String nome =  JOptionPane.showInputDialog("Digite o nome completo:");
            ArrayList<String> telefones = new ArrayList<>();
            
            String continuar = "S";

            while (continuar.equalsIgnoreCase("S")) {

                String telefone = JOptionPane.showInputDialog("Digite um telefone:");

                telefones.add(telefone);

                continuar = JOptionPane.showInputDialog("Deseja adicionar outro telefone? S/N");
            }
            
            int numCertificacao = Integer.parseInt(JOptionPane.showInputDialog("Digite o número de certificação:"));
           
            String areaEspec = JOptionPane.showInputDialog("Digite a área: Motor, Suspensão, Elétrica ou Funilaria");
            
            listaProfissional.add(new Mecanico(codigo,nome,telefones,numCertificacao,areaEspec));
            
        } 
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ImprimirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirBtnActionPerformed
        taSaida.setText("");

        for (Profissional p : listaProfissional) {
            taSaida.append(p.toString() + "\n");
        }
    }//GEN-LAST:event_ImprimirBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o código do mecânico:"));

        Profissional p = principal.buscarProfissionalCodigo(codigo);

        if (p != null) {
            listaProfissional.remove(p);
            JOptionPane.showMessageDialog(null, "Mecânico excluído com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Mecânico não encontrado!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int codigo = Integer.parseInt(
        JOptionPane.showInputDialog("Digite o código do mecânico:")
    );

    Profissional p = principal.buscarProfissionalCodigo(codigo);

    if (p != null && p instanceof Mecanico) {

        Mecanico m = (Mecanico) p;

        if (cbNome.isSelected()) {
            String novoNome = JOptionPane.showInputDialog("Digite o novo nome:");
            m.setNomeCompleto(novoNome);
        }

        if (cbTelefone.isSelected()) {
            ArrayList<String> novosTelefones = new ArrayList<>();

            String continuar = "S";

            while (continuar.equalsIgnoreCase("S")) {
                String telefone = JOptionPane.showInputDialog("Digite um telefone:");
                novosTelefones.add(telefone);

                continuar = JOptionPane.showInputDialog("Deseja adicionar outro telefone? S/N");
            }

            m.setTelefones(novosTelefones);
        }

        if (cbCertificacao.isSelected()) {
            int novaCertificacao = Integer.parseInt(
                JOptionPane.showInputDialog("Digite a nova certificação:")
            );
            m.setNumCertificacao(novaCertificacao);
        }

        if (cbArea.isSelected()) {
            String novaArea = JOptionPane.showInputDialog(
                "Digite a nova área: Motor, Suspensão, Elétrica ou Funilaria"
            );
            m.setAreaEspec(novaArea);
        }

        JOptionPane.showMessageDialog(null, "Mecânico editado com sucesso!");

    } else {
        JOptionPane.showMessageDialog(null, "Mecânico não encontrado!");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (principal.buscarProfissionalCodigo(1) == null) {

            ArrayList<String> tels1 = new ArrayList<>();
            tels1.add("(63)99999-1111");

            listaProfissional.add(
                new Mecanico(
                    1,
                    "João Silva",
                    tels1,
                    1001,
                    "Motor"
                )
            );
        }

        if (principal.buscarProfissionalCodigo(2) == null) {

            ArrayList<String> tels2 = new ArrayList<>();
            tels2.add("(63)99999-2222");

            listaProfissional.add(
                new Mecanico(
                    2,
                    "Carlos Souza",
                    tels2,
                    1002,
                    "Suspensão"
                )
            );
        }

        if (principal.buscarProfissionalCodigo(3) == null) {

            ArrayList<String> tels3 = new ArrayList<>();
            tels3.add("(63)99999-3333");

            listaProfissional.add(
                new Mecanico(
                    3,
                    "Pedro Lima",
                    tels3,
                    1003,
                    "Elétrica"
                )
            );
        }

        JOptionPane.showMessageDialog(null,"Mecânicos de teste adicionados!");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImprimirBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbArea;
    private javax.swing.JCheckBox cbCertificacao;
    private javax.swing.JCheckBox cbNome;
    private javax.swing.JCheckBox cbTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
