/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import classes.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author capsi
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());
    final ArrayList<Veiculo> listaVeiculos = new ArrayList();
    final ArrayList<Proprietario> listaProprietarios = new ArrayList<>();
    final ArrayList<Profissional> listaProfissional = new ArrayList();
    final ArrayList<Categoria> listaCategorias = new ArrayList<>();
    final ArrayList<FichaManutencao> listaFichas = new ArrayList<>();
    final ArrayList<Agendamento> listaAgendamentos = new ArrayList<>();
    /**
     * Creates new form CadastroVeiculoMecanico
     */
    
    public Categoria buscarCategoriaCodigo(int codigo) {
        for (Categoria c : listaCategorias) {
            if (c.getCodigo() == codigo) {
                return c;
            }
        }return null;
    }
    
    public Agendamento buscarAgendamentoCodigo(int codigo) {
        for (Agendamento a : listaAgendamentos) {
            if (a.getCodigo() == codigo) {
                return a;
            }
        }return null;
    }
    
    public FichaManutencao buscarFichaCodigo(int codigo) {
        for (FichaManutencao f : listaFichas) {
            if (f.getCodigo() == codigo) {
                return f;
            }
        }
        return null;
    }
    
    public FichaManutencao buscarFichaPorPlaca(String placa) {
        for (FichaManutencao f : listaFichas) {
            if (f.getVeiculo().getPlaca().equalsIgnoreCase(placa)) {
                return f;
            }
        }
        return null;
    }
    
    public Veiculo buscarVeiculoPlaca(String placa) {
        for (Veiculo v : listaVeiculos) {
            if (v.getPlaca().equalsIgnoreCase(placa)) {
                return v;
            }
        }return null;
    }
    
    public Proprietario buscarProprietarioCpf(String cpf) {
        for (Proprietario p : listaProprietarios) {
            if (p.getCpf().equalsIgnoreCase(cpf)) {
                return p;
            }
        }
        return null;
    }
    
    
    public Profissional buscarProfissionalCodigo(int cod) {
        for (Profissional p : listaProfissional) {
            if (p.getCodigo() == cod) {
                return p;
            }
        }return null;
    }

    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cadastrar Mecanicos");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Cadastrar Veiculos");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Cadastrar Categorias");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Cadastrar Ficha de Manutenção");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Gerenciar Agendamento");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastroMecanicos telaMecanicos = new CadastroMecanicos(this,true,listaProfissional);
        telaMecanicos.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CadastroVeiculos telaVeiculos = new CadastroVeiculos(
            this,
            true,
            listaVeiculos,
            listaProprietarios
        );

        telaVeiculos.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CadastroCategorias tela = new CadastroCategorias(
            this,
            true,
            listaCategorias
        );

        tela.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CadastroFichaManutencao tela = new CadastroFichaManutencao(
            this,
            true,
            listaFichas,
            listaVeiculos,
            listaCategorias,
            listaProfissional
        );

        tela.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        GerenciarAgendamento tela = new GerenciarAgendamento(
            this,
            true,
            listaProfissional,
            listaVeiculos,
            listaAgendamentos
        );
        
        tela.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
