/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import classes.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author capsi
 */
public class GerenciarAgendamento extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarAgendamento.class.getName());
    private ArrayList<Agendamento> listaAgendamentos;
    private ArrayList<Profissional> listaProfissional;
    private ArrayList<Veiculo> listaVeiculos;
    private FormPrincipal principal;
    /**
     * Creates new form GerenciarAgendamento
     * @param parent
     * @param modal
     * @param listaProfissional
     * @param listaVeiculos
     * @param listaAgendamentos
     */
    public GerenciarAgendamento(java.awt.Frame parent, boolean modal,
            ArrayList<Profissional> listaProfissional,
            ArrayList<Veiculo> listaVeiculos,
            ArrayList<Agendamento> listaAgendamentos) {
        super(parent, modal);
        this.principal = (FormPrincipal) parent;
        this.listaProfissional = listaProfissional;
        this.listaVeiculos = listaVeiculos;
        this.listaAgendamentos = listaAgendamentos;
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    private int lerInteiro(String mensagem) {
        while (true) {
            try {
                String texto = JOptionPane.showInputDialog(mensagem);

                if (texto == null) {
                    return -1;
                }

                if (texto.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Campo obrigatório!");
                } else {
                    return Integer.parseInt(texto);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Digite apenas números!");
            }
        }
    }
    
    public boolean conflitoAgendamento(String data,String hora,Veiculo veiculo,Mecanico mecanico) {

        for (Agendamento a : listaAgendamentos) {

            boolean mesmaData = a.getData().equals(data);
            boolean mesmaHora = a.getHora().equals(hora);

            if (mesmaData && mesmaHora) {

                if (a.getVeiculo().getPlaca()
                        .equalsIgnoreCase(veiculo.getPlaca())) {

                    JOptionPane.showMessageDialog(
                        null,
                        "Esse veículo já possui agendamento nesse horário!"
                    );

                    return true;
                }

                if (a.getMecanico().getCodigo()
                        == mecanico.getCodigo()) {

                    JOptionPane.showMessageDialog(
                        null,
                        "Esse mecânico já possui agendamento nesse horário!"
                    );

                    return true;
                }
            }
        }

        return false;
    }
    
    public boolean conflitoAgendamentoEdicao(String data, String hora,
        Veiculo veiculo, Mecanico mecanico, Agendamento agendamentoAtual) {

        for (Agendamento a : listaAgendamentos) {

            if (a.getCodigo() == agendamentoAtual.getCodigo()) {
                continue;
            }

            if (a.getData().equals(data) && a.getHora().equals(hora)) {

                if (a.getVeiculo().getPlaca().equalsIgnoreCase(veiculo.getPlaca())) {
                    JOptionPane.showMessageDialog(null, "Esse veículo já tem agendamento nesse horário!");
                    return true;
                }

                if (a.getMecanico().getCodigo() == mecanico.getCodigo()) {
                    JOptionPane.showMessageDialog(null, "Esse mecânico já tem agendamento nesse horário!");
                    return true;
                }
            }
        }

        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rbMecanico = new javax.swing.JRadioButton();
        rbVeiculo = new javax.swing.JRadioButton();
        rbData = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Inserir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Editar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Excluir");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Relatorio");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        buttonGroup1.add(rbMecanico);
        rbMecanico.setText("Por Mecânico");

        buttonGroup1.add(rbVeiculo);
        rbVeiculo.setSelected(true);
        rbVeiculo.setText("Por Veículo");
        rbVeiculo.addActionListener(this::rbVeiculoActionPerformed);

        buttonGroup1.add(rbData);
        rbData.setText("Por Data");

        taSaida.setColumns(20);
        taSaida.setRows(5);
        taSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório de Agendamentos"));
        jScrollPane1.setViewportView(taSaida);

        jButton5.setText("Adicionar Dados Teste");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Mostrar Agendamentos");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbVeiculo)
                            .addComponent(rbMecanico)
                            .addComponent(rbData)))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(45, 45, 45)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(rbVeiculo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMecanico)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbData)
                .addGap(31, 31, 31)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (listaVeiculos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre um veículo antes de criar um agendamento.");
            return;
        }
        
        if (listaProfissional.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre um profissional antes de criar um agendamento.");
            return;
        }
        
        
        int codigoProfissional = lerInteiro("Digite o código do profissional:");
        
        if (codigoProfissional == -1) {
            return;
        }
        
        
        String placa = JOptionPane.showInputDialog("Digite a placa do veículo:");        
        
        if (placa == null || placa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Placa é obrigatória!");
            return;
        }
     
        Veiculo veiculo = principal.buscarVeiculoPlaca(placa);
        Profissional profissional = principal.buscarProfissionalCodigo(codigoProfissional);
        
        if (veiculo == null) {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado!");
            return;
        }
        
        if (profissional == null) {
            JOptionPane.showMessageDialog(null, "Profissional não encontrado!");
            return;
        }
        
        if (!(profissional instanceof Mecanico)) {

            JOptionPane.showMessageDialog(null,"O profissional encontrado não é um mecânico!");
            return;
        }

        Mecanico mecanico = (Mecanico) profissional;
        

        
        int codigoAgendamento = lerInteiro("Digite o código do agendamento:");
        
        if (codigoAgendamento == -1) {
            return;
        }
        
        if (principal.buscarAgendamentoCodigo(codigoAgendamento) != null) {
            JOptionPane.showMessageDialog(null, "Já existe agendamento com esse código!");
            return;
        }
        
        String data = JOptionPane.showInputDialog("Digite a data (dd/MM/yyyy):");

        String hora = JOptionPane.showInputDialog("Digite a hora (HH:mm):");

        String tipoServico = JOptionPane.showInputDialog("Digite o tipo de serviço:");
        
        double valor;
        
        try {
            valor = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor:"));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um valor válido!");
            return;
        }
        
        if (data == null || data.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data é obrigatória!");
            return;
        }
        
        if (hora == null || hora.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hora é obrigatória!");
            return;
        }
                
        if (tipoServico == null || tipoServico.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tipo de serviço é obrigatório!");
            return;
        }
        

        
        if (!data.matches("\\d{2}/\\d{2}/\\d{4}")) {

            JOptionPane.showMessageDialog(
                null,
                "Data inválida! Use dd/MM/yyyy"
            );

            return;
        }
        
        if (!hora.matches("\\d{2}:\\d{2}")) {

            JOptionPane.showMessageDialog(
                null,
                "Hora inválida! Use HH:mm"
            );

            return;
        }
        
        
        if (conflitoAgendamento(data, hora, veiculo, mecanico)) {
            return;
        }
        
        Agendamento agendamento = new Agendamento(codigoAgendamento,data,hora,tipoServico,valor,veiculo,mecanico);
        listaAgendamentos.add(agendamento);
        
        JOptionPane.showMessageDialog(null,"Agendamento cadastrado com sucesso!");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int codigo = lerInteiro("Digite o código do agendamento que deseja editar:");

        if (codigo == -1) {
            return;
        }

        Agendamento agendamento = principal.buscarAgendamentoCodigo(codigo);

        if (agendamento == null) {
            JOptionPane.showMessageDialog(null, "Agendamento não encontrado!");
            return;
        }

        String novaData = JOptionPane.showInputDialog("Digite a nova data (dd/MM/yyyy):");

        if (novaData == null || novaData.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data é obrigatória!");
            return;
        }

        if (!novaData.matches("\\d{2}/\\d{2}/\\d{4}")) {
            JOptionPane.showMessageDialog(null, "Data inválida! Use dd/MM/yyyy");
            return;
        }

        String novaHora = JOptionPane.showInputDialog("Digite a nova hora (HH:mm):");

        if (novaHora == null || novaHora.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hora é obrigatória!");
            return;
        }

        if (!novaHora.matches("\\d{2}:\\d{2}")) {
            JOptionPane.showMessageDialog(null, "Hora inválida! Use HH:mm");
            return;
        }

        String novoTipoServico = JOptionPane.showInputDialog("Digite o novo tipo de serviço:");

        if (novoTipoServico == null || novoTipoServico.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tipo de serviço é obrigatório!");
            return;
        }

        double novoValor;

        try {
            novoValor = Double.parseDouble(
                JOptionPane.showInputDialog("Digite o novo valor:")
            );
            if (novoValor < 0) {JOptionPane.showMessageDialog(null,"Valor inválido!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um valor válido!");
            return;
        }

        if (conflitoAgendamentoEdicao(novaData, novaHora, agendamento.getVeiculo(), agendamento.getMecanico(), agendamento)) {
            return;
        }

        agendamento.setData(novaData);
        agendamento.setHora(novaHora);
        agendamento.setTipoServico(novoTipoServico);
        agendamento.setValor(novoValor);

        JOptionPane.showMessageDialog(null, "Agendamento editado com sucesso!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int codigo = lerInteiro("Digite o código do agendamento que deseja excluir:");

        if (codigo == -1) {
            return;
        }

        Agendamento agendamento = principal.buscarAgendamentoCodigo(codigo);

        if (agendamento == null) {
            JOptionPane.showMessageDialog(null, "Agendamento não encontrado!");
            return;
        }

        int resposta = JOptionPane.showConfirmDialog(null,"Deseja realmente excluir este agendamento?\n\n"+ agendamento,"Confirmação",JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            listaAgendamentos.remove(agendamento);

            JOptionPane.showMessageDialog(
                    null,
                    "Agendamento excluído com sucesso!"
            );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (listaAgendamentos.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                "Não há agendamentos cadastrados.");
            return;
        }
        
        
        taSaida.setText("");

        if (rbMecanico.isSelected()) {

            int codigo = lerInteiro("Digite o código do mecânico:");

            for (Agendamento a : listaAgendamentos) {

                if (a.getMecanico().getCodigo() == codigo) {

                    taSaida.append(a.toString() + "\n\n");
                }
            }

        } else if (rbVeiculo.isSelected()) {

            String placa = JOptionPane.showInputDialog("Digite a placa:");

            for (Agendamento a : listaAgendamentos) {

                if (a.getVeiculo().getPlaca().equalsIgnoreCase(placa)) {

                    taSaida.append(a.toString() + "\n\n");
                }
            }

        } else if (rbData.isSelected()) {

            String data = JOptionPane.showInputDialog("Digite a data (dd/MM/yyyy):");

            for (Agendamento a : listaAgendamentos) {

                if (a.getData().equals(data)) {

                    taSaida.append(a.toString() + "\n\n");
                }
            }

        }    
        
        if (taSaida.getText().isEmpty()) {
            taSaida.setText("Nenhum agendamento encontrado.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rbVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVeiculoActionPerformed

    }//GEN-LAST:event_rbVeiculoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (listaVeiculos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre veículos de teste primeiro.");
            return;
        }

        if (listaProfissional.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre mecânicos de teste primeiro.");
            return;
        }

        Veiculo v1 = principal.buscarVeiculoPlaca("ABC1234");
        Veiculo v2 = principal.buscarVeiculoPlaca("DEF5678");
        Veiculo v3 = principal.buscarVeiculoPlaca("GHI9012");

        Profissional p1 = principal.buscarProfissionalCodigo(1);
        Profissional p2 = principal.buscarProfissionalCodigo(2);
        Profissional p3 = principal.buscarProfissionalCodigo(3);

        if (v1 == null || v2 == null || v3 == null) {
            JOptionPane.showMessageDialog(null, "Cadastre os veículos de teste primeiro.");
            return;
        }

        if (!(p1 instanceof Mecanico) || !(p2 instanceof Mecanico) || !(p3 instanceof Mecanico)) {
            JOptionPane.showMessageDialog(null, "Cadastre os mecânicos de teste primeiro.");
            return;
        }

        Mecanico m1 = (Mecanico) p1;
        Mecanico m2 = (Mecanico) p2;
        Mecanico m3 = (Mecanico) p3;

        if (principal.buscarAgendamentoCodigo(1) == null) {
            Agendamento a1 = new Agendamento(
                    1,
                    "10/06/2026",
                    "08:00",
                    "Troca de óleo",
                    150.00,
                    v1,
                    m1
            );

            if (!conflitoAgendamento(a1.getData(), a1.getHora(), a1.getVeiculo(), a1.getMecanico())) {
                listaAgendamentos.add(a1);
            }
        }

        if (principal.buscarAgendamentoCodigo(2) == null) {
            Agendamento a2 = new Agendamento(
                    2,
                    "10/06/2026",
                    "09:00",
                    "Alinhamento e balanceamento",
                    120.00,
                    v2,
                    m2
            );

            if (!conflitoAgendamento(a2.getData(), a2.getHora(), a2.getVeiculo(), a2.getMecanico())) {
                listaAgendamentos.add(a2);
            }
        }

        if (principal.buscarAgendamentoCodigo(3) == null) {
            Agendamento a3 = new Agendamento(
                    3,
                    "11/06/2026",
                    "10:00",
                    "Revisão elétrica",
                    200.00,
                    v3,
                    m3
            );

            if (!conflitoAgendamento(a3.getData(), a3.getHora(), a3.getVeiculo(), a3.getMecanico())) {
                listaAgendamentos.add(a3);
            }
        }

        if (principal.buscarAgendamentoCodigo(4) == null) {
            Agendamento a4 = new Agendamento(
                    4,
                    "11/06/2026",
                    "14:00",
                    "Verificação de suspensão",
                    180.00,
                    v1,
                    m2
            );

            if (!conflitoAgendamento(a4.getData(), a4.getHora(), a4.getVeiculo(), a4.getMecanico())) {
                listaAgendamentos.add(a4);
            }
        }

        if (principal.buscarAgendamentoCodigo(5) == null) {
            Agendamento a5 = new Agendamento(
                    5,
                    "12/06/2026",
                    "08:30",
                    "Diagnóstico do motor",
                    250.00,
                    v2,
                    m1
            );

            if (!conflitoAgendamento(a5.getData(), a5.getHora(), a5.getVeiculo(), a5.getMecanico())) {
                listaAgendamentos.add(a5);
            }
        }

        JOptionPane.showMessageDialog(null, "Agendamentos de teste adicionados!");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        taSaida.setText("");

        taSaida.append("===== MECÂNICOS =====\n\n");

        for (Profissional p : listaProfissional) {

            if (p instanceof Mecanico) {

                Mecanico m = (Mecanico) p;

                taSaida.append(
                    "Código: " + m.getCodigo()
                    + " | Nome: " + m.getNomeCompleto()
                    + " | Especialidade: " + m.getAreaEspec()
                    + "\n"
                );
            }
        }

        taSaida.append("\n\n===== VEÍCULOS =====\n\n");

        for (Veiculo v : listaVeiculos) {

            taSaida.append(
                "Placa: " + v.getPlaca()
                + " | Modelo: " + v.getModelo()
                + " | Proprietário: " + v.getProprietario().getNome()
                + "\n"
            );
        }

        taSaida.append("\n\n===== AGENDAMENTOS =====\n\n");

        for (Agendamento a : listaAgendamentos) {

            taSaida.append(
                "Código: " + a.getCodigo()
                + " | Data: " + a.getData()
                + " | Hora: " + a.getHora()
                + " | Placa: " + a.getVeiculo().getPlaca()
                + " | Mecânico: " + a.getMecanico().getNomeCompleto()
                + "\n"
            );
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbData;
    private javax.swing.JRadioButton rbMecanico;
    private javax.swing.JRadioButton rbVeiculo;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
