/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;
import classes.Proprietario;
import classes.Veiculo;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/**
 *
 * @author novyi
 */
public class CadastroVeiculos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName());
    private ArrayList<Veiculo> listaVeiculos;
    private ArrayList<Proprietario> listaProprietarios;
    private FormPrincipal principal;
    
    /**
     * Creates new form CadastroVeiculos
     * @param parent
     * @param modal
     * @param listaProprietarios
     * @param listaVeiculos
     */
    public CadastroVeiculos(java.awt.Frame parent, boolean modal,
        ArrayList<Veiculo> listaVeiculos,
        ArrayList<Proprietario> listaProprietarios) {
        super(parent, modal);
        this.listaVeiculos = listaVeiculos;
        this.listaProprietarios = listaProprietarios;
        this.principal = (FormPrincipal) parent;
        initComponents();
        setLocationRelativeTo(parent);
        
    }
    private int lerInteiro(String mensagem) {
    String texto;
    boolean valido = false;

    do {
        texto = JOptionPane.showInputDialog(mensagem);

        if (texto == null || texto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo obrigatório!");
        } else if (!texto.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Digite apenas números!");
        } else {
            valido = true;
        }

    } while (!valido);

    return Integer.parseInt(texto);
}
    

    private CadastroVeiculos(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInserir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(this::btnInserirActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnListar.setText("Listar");
        btnListar.addActionListener(this::btnListarActionPerformed);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        jButton1.setText("Cadastrar Dados De Teste");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        String placa = JOptionPane.showInputDialog("Digite a placa do veículo:");

            if (placa == null || placa.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Placa é obrigatória!");
                return;
            }

            Veiculo veiculoAux = principal.buscarVeiculoPlaca(placa);

            if (veiculoAux == null) {
                String marca = JOptionPane.showInputDialog("Digite a marca:");

                if (marca == null || marca.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Marca é obrigatória!");
                    return;
                }

                String modelo = JOptionPane.showInputDialog("Digite o modelo:");

                if (modelo == null || modelo.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Modelo é obrigatório!");
                    return;
                }

                int anoFabricacao = lerInteiro("Digite o ano de fabricação:");

                String cor = JOptionPane.showInputDialog("Digite a cor:");

                if (cor == null || cor.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Cor é obrigatória!");
                    return;
                }

                String cpf = JOptionPane.showInputDialog("Digite o CPF do proprietário:");

                if (cpf == null || cpf.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "CPF é obrigatório!");
                    return;
                }

                Proprietario proprietarioAux = principal.buscarProprietarioCpf(cpf);

                if (proprietarioAux == null) {
                    String nome = JOptionPane.showInputDialog("Digite o nome do proprietário:");

                    if (nome == null || nome.trim().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Nome do proprietário é obrigatório!");
                        return;
                    }

                    String telefone = JOptionPane.showInputDialog("Digite o telefone do proprietário:");

                    if (telefone == null || telefone.trim().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Telefone do proprietário é obrigatório!");
                        return;
                    }

                    proprietarioAux = new Proprietario(nome, cpf, telefone);
                    listaProprietarios.add(proprietarioAux);
                }

                listaVeiculos.add(new Veiculo(placa, marca, modelo, anoFabricacao, cor, proprietarioAux));

                JOptionPane.showMessageDialog(null, "Veículo cadastrado com sucesso!");

            } else {
                JOptionPane.showMessageDialog(null, "Já existe um veículo com essa placa!");
            }
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String placa = JOptionPane.showInputDialog("Digite a placa do veículo:");

        if (placa == null || placa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Placa é obrigatória!");
            return;
        }

        Veiculo v = principal.buscarVeiculoPlaca(placa);

        if (v != null) {
            String novaMarca = JOptionPane.showInputDialog("Digite a nova marca:", v.getMarca());

            if (novaMarca != null && !novaMarca.trim().isEmpty()) {
                v.setMarca(novaMarca);
            }

            String novoModelo = JOptionPane.showInputDialog("Digite o novo modelo:", v.getModelo());

            if (novoModelo != null && !novoModelo.trim().isEmpty()) {
                v.setModelo(novoModelo);
            }

            String novoAno = JOptionPane.showInputDialog("Digite o novo ano:", v.getAnoFabricacao());

            if (novoAno != null && !novoAno.trim().isEmpty()) {
                boolean valido = false;

                while (!valido) {
                    if (novoAno.matches("[0-9]+")) {
                        v.setAnoFabricacao(Integer.parseInt(novoAno));
                        valido = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Ano inválido! Digite apenas números.");
                        novoAno = JOptionPane.showInputDialog("Digite o novo ano:", v.getAnoFabricacao());

                        if (novoAno == null || novoAno.trim().isEmpty()) {
                            valido = true;
                        }
                    }
                }
            }

            String novaCor = JOptionPane.showInputDialog("Digite a nova cor:", v.getCor());

            if (novaCor != null && !novaCor.trim().isEmpty()) {
                v.setCor(novaCor);
            }

            JOptionPane.showMessageDialog(null, "Veículo editado com sucesso!");

        } else {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        String placa = JOptionPane.showInputDialog("Digite a placa do veículo:");

        if (placa == null || placa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Placa é obrigatória!");
            return;
        }

        Veiculo v = principal.buscarVeiculoPlaca(placa);

        if (v != null) {
            listaVeiculos.remove(v);
            JOptionPane.showMessageDialog(null, "Veículo excluído com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        taSaida.setText("");

        if (listaVeiculos.isEmpty()) {
            taSaida.setText("Nenhum veículo cadastrado.");
            return;
        }

        for (Veiculo v : listaVeiculos) {
            taSaida.append(v.toString() + "\n");
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (principal.buscarVeiculoPlaca("ABC1234") == null) {

            Proprietario p1 =
                principal.buscarProprietarioCpf("11111111111");

            if (p1 == null) {
                p1 = new Proprietario(
                    "Lucas Rozendo",
                    "11111111111",
                    "(63)99999-0001"
                );

                listaProprietarios.add(p1);
            }

            listaVeiculos.add(
                new Veiculo(
                    "ABC1234",
                    "Toyota",
                    "Corolla",
                    2020,
                    "Prata",
                    p1
                )
            );
        }

        if (principal.buscarVeiculoPlaca("DEF5678") == null) {

            Proprietario p2 =
                principal.buscarProprietarioCpf("22222222222");

            if (p2 == null) {
                p2 = new Proprietario(
                    "Maria Oliveira",
                    "22222222222",
                    "(63)99999-0002"
                );

                listaProprietarios.add(p2);
            }

            listaVeiculos.add(
                new Veiculo(
                    "DEF5678",
                    "Honda",
                    "Civic",
                    2022,
                    "Preto",
                    p2
                )
            );
        }

        if (principal.buscarVeiculoPlaca("GHI9012") == null) {

            Proprietario p3 =
                principal.buscarProprietarioCpf("33333333333");

            if (p3 == null) {
                p3 = new Proprietario(
                    "José Santos",
                    "33333333333",
                    "(63)99999-0003"
                );

                listaProprietarios.add(p3);
            }

            listaVeiculos.add(
                new Veiculo(
                    "GHI9012",
                    "Chevrolet",
                    "Onix",
                    2021,
                    "Branco",
                    p3
                )
            );
        }

        JOptionPane.showMessageDialog(null,"Veículos de teste adicionados!");
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
